// vue-learn-project/src/components/TodoItem.vue
<template>
    <li>
    <span>
      <strong>{{todo.id}}</strong>
      <span v-bind:class='{done: todo.completed}'>
        <input type="checkbox" v-on:change='todo.completed = !todo.completed'/>
        {{ todo.title }}
      </span>
    </span>
    <button class="rm" v-on:click="$emit('remove-todo', todo.id)">&times;</button>
</li>
</template>

<script>
export default {
  name: 'TodoItem',
  props: {
    todo: {
        type: Object,
        required: true
    }
  },
}
</script>

<style scoped>
li {
    border: 1px solid #ccc;
    display: flex;
    justify-content: space-between;
    padding: .5rem 2rem;
    margin-bottom: 1rem;
}

.rm {
  background: red;
  color: #fff;
  border-radius: 50%;
  font-weight: bold;
}

.done {
  text-decoration: line-through;
}
</style>

// ReactJS/react-learn/src/ToDo/ToDoItem.js
import React from "react";
import { PropTypes } from "prop-types";
import "../index.css";

const styles = {
  li: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: ".5rem 1rem",
    border: "1px solid #ccc",
    borderRadius: "4px",
    marginBottom: ".5rem",
  },
  input: {
    marginRight: "1rem",
  },
};

function ToDoItem({ todo, index, onChange }) {
  const classes = [];

  if (todo.completed) {
    classes.push("done");
  }

  return (
    <li style={styles.li}>
      <span className={classes.join(" ")}>
        <input
          type="checkbox"
          checked={todo.completed}
          style={styles.input}
          onChange={() => onChange(todo.id)}
        />
        <strong>{index + 1}</strong>
        &nbsp;
        {todo.title}
      </span>

      <button className="rm">&times;</button>
    </li>
  );
}

ToDoItem.propTypes = {
  todo: PropTypes.object.isRequired,
  index: PropTypes.number,
  onChange: PropTypes.func.isRequired,
};

export default ToDoItem;
