// vue-learn-project/src/components/TodoList.vue
<template>
    <div>
        <ul class="list">
            <TodoItem
              v-for="todo in todos" :key="todo.id"
              v-bind:todo="todo"
              v-on:remove-todo="removeTodo"
            />
        </ul>
    </div>
</template>

<script>
import TodoItem from "@/components/TodoItem.vue"
export default {
  name: 'TodoList',
  props: ['todos'],
  methods: {
    removeTodo(todoId) {
      this.$emit('removeTodo', todoId)
    }
  },
  components: {
    TodoItem
  }
}
</script>

<style scoped>
  ul {
      list-style: none;
      margin: 0;
      padding: 0;
  }
</style>

// ReactJS/react-learn/src/ToDo/ToDoList.js
import React from "react";
import { PropTypes } from "prop-types";
import ToDoItem from "./ToDoItem";

const styles = {
  ul: {
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
};

function ToDoList(props) {
  return (
    <ul style={styles.ul}>
      {props.todos.map((todo, index) => {
        return (
          <ToDoItem
            todo={todo}
            key={todo.id}
            index={index}
            onChange={props.onToggle}
          />
        );
      })}
    </ul>
  );
}

ToDoList.propTypes = {
  todos: PropTypes.arrayOf(PropTypes.object).isRequired,
  onToggle: PropTypes.func.isRequired,
};

export default ToDoList;
